Repository FerretDB/dance, pull requests merged in 2022-12, with the labels that each got.

#265 Add diff tests for infinity cases
  tests/diff.yml
  tests/diff/document_validation_test.go
  tests/diff/float_values_test.go
Labels: code/chore

#271 Fix diff tests for FerretDB after validation error message changes
  tests/diff/float_values_test.go
  tests/mongo-go-driver.yml
Labels: code/chore

#275 Bump deps
  build/deps/ferretdb-textlint.Dockerfile
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#284 Create the `jstest` runner
  Taskfile.yaml
  build/deps/mongo.Dockerfile
  cmd/dance/main.go
  docker-compose.yml
  internal/jstest/jstest.go
  tests/mongo.yml
Labels: code/feature

#293 Add globs in `jstest` runner
  cmd/dance/main.go
  docker-compose.yml
  internal/gotest/gotest.go
  internal/jstest/jstest.go
  tests/mongo.yml
Labels: code/feature
