Repository FerretDB/dance, pull requests merged in 2022-11, with the labels that each got.

#230 Do not cancel in-progress CI runs
  .github/workflows/conform-pr.yml
Labels: code/chore

#235 Bump deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#220 Deprecate dotted fields in data documents
  tests/diff.yml
  tests/diff/document_validation_test.go
Labels: code/enhancement

#246 Bump deps
  build/deps/mongo6.Dockerfile
  build/deps/postgres.Dockerfile
  go.mod
  go.sum
Labels: deps

#242 Duplicate keys are not allowed in `insert` documents
  tests/diff.yml
  tests/diff/insert_test.go
Labels: code/chore

#247 Tweak and reformat docs
  .github/workflows/linters.yml
  .markdownlint.yml
  .textlintignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Taskfile.yaml
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/markdownlint.Dockerfile
  docker-compose.yml
Labels: code/chore

#251 Update Go driver tests to make CI pass
  tests/mongo-go-driver.yml
Labels: code/chore

#252 Deprecate float values
  tests/diff.yml
  tests/diff/float_values_test.go
Labels: code/enhancement

#258 Allow `-` in database names
  tests/diff.yml
  tests/diff/names_test.go
Labels: code/enhancement

#259 Do not handle `no ci` in one job
  .github/workflows/conform-pr.yml
Labels: code/bug
