Repository FerretDB/dance, pull requests merged in 2022-07, with the labels that each got.

#157 Bump deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#163 Add diff tests for NUL `\0` strings
  tests/diff.yml
  tests/diff/null_strings_test.go
Labels: code/chore

#161 Add regex support for test cases
  internal/config.go
  internal/config_test.go
  internal/tests_config.go
  internal/yaml_test_processor.go
Labels: code/feature

#153 Enable Go driver's integration tests
  docker-compose.yml
  tests/mongo-go-driver.yml
Labels: code/enhancement

#176 Validate database names
  tests/diff.yml
  tests/diff/helpers.go
  tests/diff/names_test.go
  tests/diff/setup.go
Labels: code/feature

#181 Update deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: code/chore
