Repository FerretDB/dance, pull requests merged in 2023-03, with the labels that each got.

#356 Use Go 1.20
  go.mod
  go.sum
  tools/check.go
  tools/go.mod
  tools/go.sum
  tools/old.go
  tools/tools.go
Labels: deps

#357 Dependabot/go modules/go.mongodb.org/mongo driver 1.11.2
  go.mod
Labels: deps

#375 Show submodules in `git diff`
  .github/workflows/dance.yml
Labels: code/chore

#376 Optimize `jstest` runner
  internal/jstest/jstest.go
Labels: code/enhancement

#381 Bump Go deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#386 Fix Go driver for CI
  tests/mongo-go-driver.yml
Labels: code/chore

#374 Add diff tests for collection and database name
  tests/diff.yml
  tests/diff/names_test.go
Labels: code/enhancement

#382 Allow `jstest` runner to load files using a relative path
  docker-compose.yml
  internal/jstest/jstest.go
Labels: code/bug

#366 Add more jstests
  tests/mongo.yml
Labels: code/chore

#387 Fix `mongo` configuration
  tests/mongo.yml
Labels: code/chore

#388 Limit the number of parallel files for `jstest` runner
  internal/jstest/jstest.go
Labels: code/enhancement

#395 Fix Go driver config
  tests/mongo-go-driver.yml
Labels: code/chore

#394 Bump deps
  tools/go.mod
  tools/go.sum
Labels: deps
