Repository FerretDB/dance, pull requests merged in 2023-11, with the labels that each got.

#645 Remove diff tests that were moved to FerretDB
  Taskfile.yaml
  go.mod
  go.sum
  tests/diff/dbstats_scale_test.go
  tests/diff/debug_error_test.go
  tests/diff/document_validation_test.go
  tests/diff/error_messages_test.go
  tests/diff/float_values_test.go
  tests/diff/helpers.go
  tests/diff/insert_test.go
  tests/diff/names_test.go
  tests/diff/negative_zero_test.go
  tests/diff/nested_arrays_test.go
  tests/diff/null_strings_test.go
  tests/diff/update_test.go
Labels: code/chore

#658 Bump Go and tools deps
  CONTRIBUTING.md
  README.md
  Taskfile.yaml
  build/deps/ferretdb-textlint.Dockerfile
  build/deps/postgres.Dockerfile
  docker-compose.yml
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#668 Fix enmeshed config
  cmd/dance/main.go
  tests/enmeshed-runtime.yml
Labels: code/chore, trust

#669 Fix trust configuration
  .github/workflows/dance-trust.yml
Labels: trust

#671 Retain failure logs for longer
  .github/workflows/dance-trust.yml
  .github/workflows/dance.yml
Labels: code/chore
