Repository FerretDB/dance, pull requests merged in 2023-06, with the labels that each got.

#449 Add `ycsb` runner and add to CI
  .github/workflows/dance.yml
  cmd/dance/main.go
  internal/config.go
  internal/ycsb/ycsb.go
  tests/ycsb/workloads/workload_template
  tests/ycsb/workloads/workloada
  tests/ycsb/workloads/workloadb
  tests/ycsb/workloads/workloadc
  tests/ycsb/workloads/workloadd
  tests/ycsb/workloads/workloade
  tests/ycsb/workloads/workloadf
  tests/ycsb1.yml
  tests/ycsb2.yml
Labels: code/feature

#466 Add diff for `findandmodify` dollar prefixed field name
  tests/diff.yml
  tests/diff/document_validation_test.go
Labels: code/chore

#471 Bump deps
  .golangci-new.yml
  .golangci.yml
  build/deps/ferretdb-textlint.Dockerfile
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#473 Add all files for the dbaas_core suite
  internal/jstest/jstest.go
  tests/dbaas_core.yml
Labels: code/chore

#474 Set `TestData` object to allow more tests to run
  internal/jstest/jstest.go
  tests/dbaas_core.yml
  tests/mongo.yml
Labels: code/chore

#493 Fix diff test
  tests/diff/dbstats_scale_test.go
Labels: code/bug

#497 Bump Go deps
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps

#494 Add more aggregation tests
  tests/mongo.yml
Labels: code/chore
