Repository FerretDB/dance, pull requests merged in 2023-10, with the labels that each got.

#600 Remove regex support
  internal/config/config.go
  internal/configload/configload.go
  internal/configload/configload_test.go
Labels: code/chore

#606 Remove dependency on common section
  internal/configload/configload.go
  internal/configload/configload_test.go
Labels: code/chore

#607 Change YAML tag
  internal/configload/configload.go
  internal/configload/configload_test.go
Labels: code/chore

#611 Refactor more
  internal/config/config.go
  internal/configload/backend.go
  internal/configload/configload.go
  internal/configload/configload_test.go
  internal/configload/stats.go
  internal/gotest/gotest.go
Labels: code/chore

#612 Sort names only once
  internal/configload/backend.go
Labels: code/enhancement

#597 Fix and reorganize all config files
  .github/workflows/dance.yml
  tests/dbaas_core-0.yml
  tests/dbaas_core-1.yml
  tests/dbaas_core-2.yml
  tests/dbaas_core-3.yml
  tests/dotnet-example-auth.yml
  tests/dotnet-example.yml
  tests/enmeshed-runtime.yml
  tests/java-example-auth.yml
  tests/java-example.yml
  tests/mongo-go-driver.yml
  tests/mongo-tools.yml
  tests/mongo.yml
  tests/python-example-auth.yml
  tests/python-example.yml
  tests/ycsb-workloada.yml
  tests/ycsb-workloadc.yml
Labels: code/chore

#614 Fix all config files
  internal/config/config.go
  tests/dbaas_core-0.yml
  tests/dbaas_core-1.yml
  tests/dbaas_core-2.yml
  tests/dbaas_core-3.yml
  tests/diff.yml
  tests/dotnet-example-auth.yml
  tests/dotnet-example.yml
  tests/enmeshed-runtime.yml
  tests/java-example-auth.yml
  tests/java-example.yml
  tests/mongo-go-driver.yml
  tests/mongo-tools.yml
  tests/mongo.yml
  tests/python-example-auth.yml
  tests/python-example.yml
  tests/ycsb-workloada.yml
  tests/ycsb-workloadc.yml
Labels: code/chore

#624 Add capped collection tests
  tests/mongo.yml
Labels: code/chore

#626 Add all tailable cursor tests
  tests/mongo-go-driver.yml
  tests/mongo.yml
Labels: code/chore

#630 Bump deps
  .github/workflows/dance-trust.yml
  .github/workflows/dance.yml
  .github/workflows/linters.yml
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: deps
