Repository FerretDB/dance, pull requests merged in 2023-08, with the labels that each got.

#536 Bump Go deps
  .github/workflows/conform-pr.yml
  .github/workflows/dance.yml
  .github/workflows/linters.yml
  go.mod
  go.sum
  tests/dotnet-example-auth.yml
  tests/dotnet-example.yml
  tests/java-example-auth.yml
  tests/java-example.yml
  tests/python-example-auth.yml
  tests/python-example.yml
  tests/ycsb/workloads/workloadd
  tests/ycsb/workloads/workloadf
  tools/go.mod
  tools/go.sum
Labels: deps

#548 Run Enmeshed tests on CI
  .github/mergify.yml
  .github/settings.yml
  .github/workflows/conform-pr.yml
  .github/workflows/dance-trust.yml
  .github/workflows/dance.yml
  .github/workflows/linters.yml
  .gitmodules
  go.mod
  go.sum
  internal/command/command.go
  tests/dotnet-example.yml
  tests/enmeshed-runtime.sh
  tests/enmeshed-runtime.yml
  tests/java-example-auth.sh
  tests/java-example-auth.yml
  tests/java-example.sh
  tests/java-example.yml
  tests/python-example-auth.sh
  tests/python-example-auth.yml
  tests/python-example.sh
  tests/python-example.yml
  tools/go.mod
  tools/go.sum
Labels: code/feature, trust

#549 Add a guide for custom tests
  CONTRIBUTING.md
Labels: documentation

#562 Split the dbaas_core config to run in parallel
  .github/workflows/dance.yml
  tests/dbaas_core-0.yml
  tests/dbaas_core-1.yml
  tests/dbaas_core-2.yml
  tests/dbaas_core-3.yml
Labels: code/chore
