Repository FerretDB/dance, pull requests merged in 2025-03, with the labels that each got.

#1184 Use v1 images
  .github/workflows/dance-trust.yml
  .github/workflows/dance.yml
  .github/workflows/go.yml
  Taskfile.yaml
Labels: deps

#1182 Add FerretDB v2 configurations
  .github/workflows/dance-trust.yml
  .github/workflows/dance.yml
  .github/workflows/go.yml
  CONTRIBUTING.md
  build/mongod_secured.conf
  docker-compose.yml
  internal/configload/configload.go
  projects/dotnet-example.yml
  projects/java-example.yml
  projects/mongo-tools.yml
  projects/python-example.yml
  projects/ycsb-workloada.yml
  projects/ycsb-workloadb.yml
  projects/ycsb-workloadc.yml
Labels: code/chore

#1199 Add v2 dev databases
  docker-compose.yml
  internal/configload/configload.go
  projects/dotnet-example.yml
  projects/java-example.yml
  projects/mongo-tools.yml
  projects/nodejs-example.yml
  projects/python-example.yml
  projects/ycsb-workloada.yml
  projects/ycsb-workloada2.yml
  projects/ycsb-workloadb.yml
  projects/ycsb-workloadb2.yml
  projects/ycsb-workloadc.yml
  projects/ycsb-workloadc2.yml
Labels: code/chore

#1209 Update MongoDB to 8.0.6
  build/deps/mongo.Dockerfile
Labels: deps

#1211 Update Mergify config
  .github/mergify.yml
Labels: not ready
